### ISSUE TITLE
Does not show up in Foundry v11

### ISSUE THREAD

**Issue by pafvel** [DC23/jd-easytimekeeping#131]
The UI doesn't show up in Foundry v11.315, but the manifest says it works for v11.
No warnings or errors in the console.

Version tested: v0.6.6

**Comment by DC23** [comment]
Uh oh, that's a bug in the manifest. I've used the new ApplicationV2 classes which means the module is v12+ only. Early in development it was v11 compatible, but I forgot to update the module file when I started work on the UI.
